### ISSUE TITLE
Instagram login not working

### ISSUE THREAD

**Issue by Julio0250** [pennersr/django-allauth#2454]
Well , the first error says:

{"error_type": "OAuthException", "code": 400, "error_message": "Invalid scope: ['basic']"}

So i look into instagram documentation and they set 2 scopes, user_profile and user_media

```
https://api.instagram.com/oauth/authorize
  ?client_id={app-id}
  &redirect_uri={redirect-uri}
  &scope=user_profile,user_media
  &response_type=code
```
Knowing that, i made a change in the url

 `https://www.instagram.com/oauth/authorize?client_id=some_id&redirect_uri=https://127.0.0.1:8000/accounts/instagram/login/callback/&scope=**basic**&response_type=code&state=sdkVg0ajfb5Z`

from scope=basic to scope=user_profile

It worked, instagram ask me for permissions and after authorize, it throws a new error 

Social Network Login Failure

`An error occurred while attempting to login via your social network account.`

and gave me this url: https://127.0.0.1:8000/accounts/instagram/login/callback/?code=some_code&state=sdkVg0ajfb5Z#_

With facebook all its working fine.

If someone can help me, it will be much appreciate

**Comment by zachmccormick** [comment]
I believe I fixed it with https://github.com/pennersr/django-allauth/pull/2514

You don't get a profile picture anymore with their new API though :-/

**Comment by tsouvarev** [comment]
@zachmccormick I still get this error
also, changing scope from `basic` to `user_profile` in URL doesn't fix error: instagram says that `Invalid scope field(s): basic,user_profile`

**Comment by RobinHoutevelts** [comment]
I'm also having that issue.

https://www.instagram.com/oauth/authorize?state=784aexxxxxxxxxxxx4&scope=user_profile&response_type=code&approval_prompt=auto&redirect_uri=https://www.xxxxxxxx.be/login&client_id=3c9xxxxxxxxxx40b0e4d

Gives me:

```
Invalid scope field(s): basic,user_profile
```

But I'm only asking for `user_profile` 😭

**Comment by iarp** [comment]
For now you can set scopes via settings:

```python
SOCIALACCOUNT_PROVIDERS = {
    'instagram': {
        'SCOPE': ['user_profile'],
    }
}
```

**Comment by pennersr** [comment]
Closed via #2514

**Comment by BarnabasSzabolcs** [comment]
@pennersr You're doing an awesome job, managing so many changing api's at once! 
The default Instagram SCOPE should be ['user_profile'], as it cannot be [] and it cannot be ['basic'] either.
Instagram has an undocumented api, `https://www.instagram.com/{username}/?__a=1`, that works most of the time. It also provides full_name and avatar_url.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2454
