### ISSUE TITLE
Unable to login to twitch

### ISSUE THREAD

**Issue by dnpthree** [pennersr/django-allauth#2537]
I've created multiple vanilla loads and had a known good configuration. I am no longer able to login to twitch and know they have made recent changes to their API (this might be the issue)

I believe this could be due to the switch to the new Kraken API https://dev.twitch.tv/docs/authentication/#sending-user-access-and-app-access-tokens

**Comment by alex-ong** [comment]
I also can't log into twitch.

**Comment by alex-ong** [comment]
Fixed it.
In allauth.socialaccount.providers.twitch.views.py
```
        headers = { 'client-id': app.client_id, #this line is new.
                    'Authorization': 'Bearer {}'.format(token.token)}
```

**Comment by dnpthree** [comment]
> Fixed it.
> In allauth.socialaccount.providers.twitch.views.py
> 
> ```
>         headers = { 'client-id': app.client_id, #this line is new.
>                     'Authorization': 'Bearer {}'.format(token.token)}
> ```

This actually still didn't work for me and was already in the most recent version. Is it working for you now?

**Comment by alex-ong** [comment]
I fixed it by doing that, then when i went to go make a pull request, found that it was already in master.

So until this gets migrated into PyPI, my project is using this:
Note that just using plain master might not work since it's failing builds. I went to the latest master commit where builds weren't broken.

**Pipfile for pipenv**
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
django = "==3.0.6"
django-allauth = {git = "https://github.com/pennersr/django-allauth.git",ref = "c02dd0557133bb843b97a02f96ca478f64ed4b53"}

[requires]
python_version = "3.7"
```

**Comment by dnpthree** [comment]
I have followed the instructions 10x. Regenerated my tokens. Verified my URLs. Updated the packages for my project to the latest release and I still get this... This is breaking everything for my app.
{'provider': 'twitch', 'code': 'unknown', 'exception': OAuth2Error('Twitch API Error: Unauthorized (Client ID and OAuth token do not match)')}

**Comment by dnpthree** [comment]
@alex-ong Your fix worked great. I ended up using this command to test it out in my requirements.txt

-e git+https://www.github.com/pennersr/django-allauth.git#egg=dc2c717ec87b07d368f1e552f76474e931a175a5

Can't thank you enough for the help!

**Comment by beheh** [comment]
I fixed this #2527, so I believe this issue can be closed (or once a new version has been released).

**Comment by alex-ong** [comment]
Thanks for the fix beheh

**Comment by alex-ong** [comment]
@pennersr Just wondering when the next PyPI release is scheduled? Just so there's a rough ETA for users (like me) who prefer to use PyPI versions rather than pointing at master; and also since people pulling off PyPI will be hit with this and find it hard to find this particular issue since it's closed.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2537
